### ISSUE TITLE
Home Page - Featured Image

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-coders#187]
Please set the featured image to be full width.

**Comment by nt6726** [comment]
I made it so that the image is the full width of the page. However, the image height was stretched as well. I could not figure out how to get it to span full width without stretching the height. Also, I could not set the image size of a featured image, so I had to remove the featured image and add the image manually on the page.

**Comment by Code4SocialGood** [comment]
Works fine, closing the issue.
